SkillsetTracker live lab updated
oracle-livelabs/adb pull request #10
Opened 2022-07-08 09:30 UTC by av131996

2022-07-08 21:37 UTC, arabellayao requested changes
Hi! Please include the workshop's WMS ID in the title of your PR. Thanks!

2022-07-11 07:14 UTC, av131996 commented
> Hi! Please include the workshop's WMS ID in the title of your PR. Thanks!

WMS ID added. Thank you!

2022-07-11 08:45 UTC, madhusudhanrao-ppm approved these changes

2022-07-11 10:51 UTC, madhusudhanrao-ppm approved these changes

2022-07-11 10:52 UTC, merged